#!/usr/bin/env bash
# Auto-detects project languages and writes guidelines/active.md
# Called by Claude Code UserPromptSubmit hook.
#
# Usage: bash detect-languages.sh [project_root]
# Defaults to CWD if no project_root given.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${1:-$(pwd)}"
GUIDELINES_DIR="$SCRIPT_DIR/../../guidelines"
OUTPUT_FILE="$PROJECT_ROOT/guidelines/active.md"

# Resolve real path
GUIDELINES_DIR="$(cd "$GUIDELINES_DIR" && pwd)"

mkdir -p "$PROJECT_ROOT/guidelines"

DETECTED=()

has_files() {
    find "$PROJECT_ROOT" -maxdepth 4 \
        -not -path "*/node_modules/*" \
        -not -path "*/.git/*" \
        -not -path "*/vendor/*" \
        -name "$1" 2>/dev/null | grep -q .
}

manifest_exists() {
    [ -f "$PROJECT_ROOT/$1" ]
}

# --- Detection ---

# Python
if manifest_exists "pyproject.toml" || manifest_exists "requirements.txt" || \
   manifest_exists "setup.py" || manifest_exists "setup.cfg" || \
   has_files "*.py"; then
    DETECTED+=("python")
fi

# TypeScript (check before JS to avoid double-detection)
if manifest_exists "tsconfig.json" || has_files "*.ts" || has_files "*.tsx"; then
    DETECTED+=("typescript")
fi

# JavaScript (only if TypeScript not detected)
already_ts=false
for lang in "${DETECTED[@]+"${DETECTED[@]}"}"; do
    [ "$lang" = "typescript" ] && already_ts=true
done
if ! $already_ts; then
    if manifest_exists "package.json" || has_files "*.js" || has_files "*.jsx"; then
        DETECTED+=("javascript")
    fi
fi

# Go
if manifest_exists "go.mod" || has_files "*.go"; then
    DETECTED+=("go")
fi

# Java
if manifest_exists "pom.xml" || manifest_exists "build.gradle" || has_files "*.java"; then
    DETECTED+=("java")
fi

# Kotlin
if manifest_exists "build.gradle.kts" || has_files "*.kt"; then
    DETECTED+=("kotlin")
fi

# Rust
if manifest_exists "Cargo.toml" || has_files "*.rs"; then
    DETECTED+=("rust")
fi

# --- Write active.md ---

inject_if_exists() {
    local guide="$GUIDELINES_DIR/$1"
    if [ -f "$guide" ]; then
        echo "---"
        echo ""
        cat "$guide"
        echo ""
    fi
}

# --- Signal detection for conditional guidelines ---

is_web_or_api=false
if [ -f "$PROJECT_ROOT/Dockerfile" ] || [ -f "$PROJECT_ROOT/docker-compose.yml" ] || \
   [ -f "$PROJECT_ROOT/docker-compose.yaml" ] || [ -f "$PROJECT_ROOT/pom.xml" ] || \
   [ -f "$PROJECT_ROOT/build.gradle" ] || [ -f "$PROJECT_ROOT/build.gradle.kts" ]; then
    is_web_or_api=true
fi

is_db=false
if [ -d "$PROJECT_ROOT/migrations" ] || [ -d "$PROJECT_ROOT/prisma" ] || \
   [ -f "$PROJECT_ROOT/alembic.ini" ] || [ -d "$PROJECT_ROOT/db" ] || \
   find "$PROJECT_ROOT" -maxdepth 3 -name "*.sql" 2>/dev/null | grep -q .; then
    is_db=true
fi

is_deployment=false
if [ -f "$PROJECT_ROOT/Dockerfile" ] || [ -f "$PROJECT_ROOT/docker-compose.yml" ] || \
   [ -f "$PROJECT_ROOT/docker-compose.yaml" ] || [ -d "$PROJECT_ROOT/k8s" ] || \
   [ -d "$PROJECT_ROOT/kubernetes" ]; then
    is_deployment=true
fi

frontend=false
for lang in "${DETECTED[@]+"${DETECTED[@]}"}"; do
    [ "$lang" = "typescript" ] || [ "$lang" = "javascript" ] && frontend=true && break
done

{
    echo "# Active Language Guidelines"
    echo ""
    echo "<!-- Auto-generated by .claude/hooks/detect-languages.sh — do not edit manually -->"
    echo "<!-- Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ') -->"
    echo ""

    if [ ${#DETECTED[@]} -eq 0 ]; then
        echo "No specific language detected. Applying base guidelines only."
    else
        echo "**Detected languages:** ${DETECTED[*]}"
        echo ""
    fi

    # Language-specific guidelines
    for lang in "${DETECTED[@]+"${DETECTED[@]}"}"; do
        inject_if_exists "$lang.md"
    done

    # Always-on production guidelines
    inject_if_exists "observability.md"
    inject_if_exists "testing.md"
    inject_if_exists "branching.md"
    inject_if_exists "dependencies.md"
    inject_if_exists "adr.md"

    # Conditional: web/API signals
    if $is_web_or_api; then
        inject_if_exists "api-design.md"
    fi

    # Conditional: database signals
    if $is_db; then
        inject_if_exists "database.md"
    fi

    # Conditional: deployment signals
    if $is_deployment; then
        inject_if_exists "feature-flags.md"
        inject_if_exists "incidents.md"
    fi

    # Conditional: frontend signals (TypeScript or JavaScript)
    if $frontend; then
        inject_if_exists "accessibility.md"
    fi

} > "$OUTPUT_FILE"

if [ ${#DETECTED[@]} -eq 0 ]; then
    echo "No specific language detected. Language detection complete."
else
    echo "Language detection complete. Detected: ${DETECTED[*]}"
fi
