{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fkblitz.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fkblitz.labels" . | nindent 4 }}
type: Opaque
stringData:
  FKBLITZ_ADMIN_PASSWORD: {{ .Values.secret.adminPassword | quote }}
  {{- if .Values.redis.enabled }}
  REDIS_PASSWORD: {{ .Values.secret.redisPassword | quote }}
  {{- end }}
  {{- if .Values.oauth2.enabled }}
  OAUTH2_CLIENT_SECRET: {{ .Values.secret.oauth2ClientSecret | quote }}
  {{- end }}
{{- end }}
